// <auto-generated />
using System;
using Hotel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Domain.Guests.Guest", b =>
                {
                    b.Property<long>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("guest_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuestId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("GuestId");

                    b.ToTable("guest", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Guests.GuestIdentity", b =>
                {
                    b.Property<long>("GuestId")
                        .HasColumnType("bigint")
                        .HasColumnName("guest_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Citizenship")
                        .HasColumnType("text")
                        .HasColumnName("citizenship");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_number");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text")
                        .HasColumnName("issued_by");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.HasKey("GuestId");

                    b.ToTable("guest_identity", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Identity.AppUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.MealPlan", b =>
                {
                    b.Property<long>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("meal_plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MealPlanId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerPersonPerDay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_per_person_per_day");

                    b.HasKey("MealPlanId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meal_plan", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_plan_price_positive", "\"price_per_person_per_day\" >= 0");
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Reservation", b =>
                {
                    b.Property<long>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReservationId"));

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<int>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text");

                    b.Property<long?>("MealPlanId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PlannedCheckin")
                        .HasColumnType("date")
                        .HasColumnName("planned_checkin");

                    b.Property<DateOnly>("PlannedCheckout")
                        .HasColumnType("date")
                        .HasColumnName("planned_checkout");

                    b.Property<decimal?>("Prepayment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("prepayment");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_price");

                    b.HasKey("ReservationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MealPlanId");

                    b.ToTable("reservation", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservation_adults", "\"adults\" >= 1");

                            t.HasCheckConstraint("ck_reservation_dates", "\"planned_checkout\" > \"planned_checkin\"");
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.ReservationRoom", b =>
                {
                    b.Property<long>("ReservationRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservation_room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReservationRoomId"));

                    b.Property<decimal?>("PricePerNight")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_per_night");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("ReservationRoomId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("reservation_room", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Stay", b =>
                {
                    b.Property<long>("StayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("stay_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StayId"));

                    b.Property<DateTimeOffset?>("ActualCheckin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualCheckout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MealPlanId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PlannedCheckin")
                        .HasColumnType("date")
                        .HasColumnName("planned_checkin");

                    b.Property<DateOnly>("PlannedCheckout")
                        .HasColumnType("date")
                        .HasColumnName("planned_checkout");

                    b.Property<long?>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("StayId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("stay", null, t =>
                        {
                            t.HasCheckConstraint("ck_stay_dates", "\"planned_checkout\" > \"planned_checkin\"");
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.StayGuest", b =>
                {
                    b.Property<long>("StayId")
                        .HasColumnType("bigint")
                        .HasColumnName("stay_id");

                    b.Property<long>("GuestId")
                        .HasColumnType("bigint")
                        .HasColumnName("guest_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.HasKey("StayId", "GuestId");

                    b.HasIndex("GuestId");

                    b.ToTable("stay_guest", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Rooms.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoomId"));

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_number");

                    b.Property<long>("RoomTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_type_id");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("Hotel.Domain.Rooms.RoomType", b =>
                {
                    b.Property<long>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("room_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("room_type", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_type_base_price_non_negative", "\"base_price\" >= 0");

                            t.HasCheckConstraint("ck_room_type_capacity_positive", "\"capacity\" > 0");
                        });
                });

            modelBuilder.Entity("Hotel.Domain.Guests.GuestIdentity", b =>
                {
                    b.HasOne("Hotel.Domain.Guests.Guest", "Guest")
                        .WithOne("GuestIdentity")
                        .HasForeignKey("Hotel.Domain.Guests.GuestIdentity", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Reservation", b =>
                {
                    b.HasOne("Hotel.Domain.Identity.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Hotel.Domain.Reservations.MealPlan", "MealPlan")
                        .WithMany("Reservations")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.ReservationRoom", b =>
                {
                    b.HasOne("Hotel.Domain.Reservations.Reservation", "Reservation")
                        .WithMany("Rooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Rooms.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Stay", b =>
                {
                    b.HasOne("Hotel.Domain.Identity.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Hotel.Domain.Reservations.MealPlan", "MealPlan")
                        .WithMany("Stays")
                        .HasForeignKey("MealPlanId");

                    b.HasOne("Hotel.Domain.Reservations.Reservation", "Reservation")
                        .WithMany("Stays")
                        .HasForeignKey("ReservationId");

                    b.HasOne("Hotel.Domain.Rooms.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MealPlan");

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.StayGuest", b =>
                {
                    b.HasOne("Hotel.Domain.Guests.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.Domain.Reservations.Stay", "Stay")
                        .WithMany("Guests")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Hotel.Domain.Rooms.Room", b =>
                {
                    b.HasOne("Hotel.Domain.Rooms.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Hotel.Domain.Guests.Guest", b =>
                {
                    b.Navigation("GuestIdentity");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.MealPlan", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Stays");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Reservation", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Stays");
                });

            modelBuilder.Entity("Hotel.Domain.Reservations.Stay", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Hotel.Domain.Rooms.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
